### ISSUE TITLE
Optional DataInterfaces

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#184]
**Problem:** 
Converters with multiple DataInterfaces are too rigid and force the user to pass the `source_data` for every DataInterface at their instantiation, but in some cases we might want to be flexible and allow for a given DataInterface to be optional. 
`MovshonBlackrockNWBConverter` for example, where the user might have only raw or processed data files, but not both. I presume a similar problem could occur in `PoissonClicksNWBConverter`, @CodyCBakerPhD ?

A Converter factory function would work for simple cases in principle, but we would loose any custom overridden methods implemented for that lab’s specific converter.

Any ideas?

**Comment by bendichter** [comment]
https://github.com/catalystneuro/nwb-conversion-tools/blob/d08c3dc30ecdc02c82b6a7d4495343ea1a759715/nwb_conversion_tools/nwbconverter.py#L65

You should be able to omit the source data for any particular DataInterface, in which case it won't be initialized.

**Comment by CodyCBakerPhD** [comment]
So, what Ben says is true and right now is the suggested approach.

However, [Issue #163](https://github.com/catalystneuro/nwb-conversion-tools/issues/163) offers a different solution of direct modification of interfaces post-instantiation, which has been voted down due to its potential for causing errors.

I have indeed run into this use case many times before and thus far I've used Ben's suggestions acting on an NWBConverter class that was built with the maximum number of possible interface classes, even if some of them do not end up being instantiated by the `source_data`.

That said, all the times I have run into this are situations where I am converting an entire existing dataset, where some subset of the sessions have missing files from various formats. The version of dynamic generation of NWBConverter classes that I think we are landing on should be able to generate a `data_interface_class` list on the fly based on available data utilizing the `type` function, but perhaps taking as input a list of maximal possible data interface classes that might be expected to occur.

> A Converter factory function would work for simple cases in principle, but we would loose any custom overridden methods implemented for that lab’s specific converter.

Not true if we use the `type` function - you can still build those same overrides and pass them as arguments alongside the attributes.

**Comment by CodyCBakerPhD** [comment]
That said, the one downside to including more data interface classes into a converter than source_data are specified comes down to retrieving the initial source schemas. This is the argument against a Frankenstein NWBConverter that contains all possible data interfaces, but only intended to instantiate a small subset of those, because its schemas would contain and return all possibilities (not very informative to a user).

**Comment by luiztauffer** [comment]
I've tested the omitting source_data entries approach and it seems to work well, I haven't  spotted any problems so far. I'm closing this Issue for now
