### ISSUE TITLE
OpenCV should not be a requirement

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-conversion-tools#206]
## Description

OpenCV should not be required for labs that do not use MovieInterface

## Steps to Reproduce

Problem appeared here:
https://github.com/catalystneuro/mease-lab-to-nwb/issues/43#issuecomment-875557235

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.5, 3.6, or 3.7
    Operating System: Windows, macOS or Linux
    HDMF Version: version of HDMF (see using `pip show hdmf`)
    PyNWB Version: ...
    spikeextractors Version: ...
    roiextractors Version: ...
    

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer @bendichter Thanks for the report! This has already been reported and fixed in v0.8.4. Are you sure it is still an issue for the current version (v0.8.5)? I just did a full fresh install on a new conda environment and it worked fine on master.

> ## Checklist
> * [x]  Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

This item is on the checklist to remind us to search for such things so we don't make needless duplicates. A single search for "opencv" led directly to [PR #164](https://github.com/catalystneuro/nwb-conversion-tools/pull/164), which included the fix.

Also, be sure to include the versions of dependencies (and nwb_conversion_tools itself) in that part of the issue form, since this is entirely a version issue as is.

**Comment by CodyCBakerPhD** [comment]
@luiztauffer The Mease lab indicated that master branch (v0.8.5) fixed that part of their issue. Can this be closed?
