### ISSUE TITLE
refactoring new spike interface objects

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#335]
As we have been using the new SpikeInterface objects, some issues have come up that require changes on the architectural level. The problem stems from the fact that the objects are trying to do too much- they are standardizing the read between the two different versions of SpikeInterface and they are automating the conversion. Not only is this sub-optimal from a software engineering perspective, the new method misses a lot of the lessons we learned along the way with writing. As I have been exploring, I have found issues with:
* applying conversion factors
* modularization and optional arguments for writing specific components
* issues with sub-extractors
* issues with DataChunkIterator

I'd like to revert our master branch to 0.9.4, apply the other commits since then, and move our current master to a dev branch. In that dev branch, I would like to change our approach so that we have an object that simply standardizes read, and we make minimal changes to the 0.9.4 write functions so that they can take this object as input.

**Comment by CodyCBakerPhD** [comment]
On it - I'll put together a task list here for sub-PRs on minor versions.

**Comment by CodyCBakerPhD** [comment]
To-Do's to restore non-writer state changes...

- [ ] BaseDataInterface docstrings and deprecation removal  (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-bf858bbc028b29755d9b73db977f52e99f2941956d1648d8ca45bb0afcd97230L1-L47)
- [ ] Axona interface fixes, tests, and input remapping (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-e4ae9f8f87443c7fb2199d717731fb63cb6da945a87aad6ac4d5600ae1fe11a5L1-R545)
- [ ] Blackrock fixe, tests, and input remapping (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-587cde4319f00c277f5710dba38983977721079c90120846135d6cda2ae49575L14-R92)
- [ ] CED fixes and tests, including mac-specific versioning assertion (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-587cde4319f00c277f5710dba38983977721079c90120846135d6cda2ae49575L14-R92)
- [ ] CellExplorer fixes (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-587cde4319f00c277f5710dba38983977721079c90120846135d6cda2ae49575L14-R92)
- [ ] Neuroscope fixes and tests (https://github.com/catalystneuro/nwb-conversion-tools/compare/v0_10_3?expand=1#diff-5382d036dfc1f0e9ce967cff3e4640db3141a5021706d13886e47cb1ed6844daL118-R287)
- [ ] Other interface input remappings

Each of these will be opened in a separate minimal PR, which may be expedited under previous approvals if and only if all tests are passing for each set of changes.

Adding more to this over time as I comb through the changelog.

**Comment by CodyCBakerPhD** [comment]
The previous state of `master` has now been backed up to the `v0_10_3` branch for reference of all the valuable work that had been done there, but needs incremental merging with heavy testing associated with each minimal addition.

The current default branch is `main` which will be bumped to version `0.9.5` (once the Neuroscope and CellExplorer are restored) in collecting all the minor bug fixes from the last month and a half. Turns out it was much easier to resolve commit history by creating this new branch from the `0.9.4` commit hash, then steadily folding in non-`EphysWriter` changes piece by piece. Also brings us into the new age of default branch naming conventions.

A good first PR for re-merging these SpikeInterface version related changes would be a limited PR (+/- 200 lines) that merely introduces a generalized `SpikeInterfaceRecording(recording_object=some_extractor_or_recording)` class, an API that functions as a `BaseRecording` object from `spikeinterface/spikeinterface`, but conveniently wraps either a `BaseRecording` object or the older `RecordingExtractor` object type and allows all inherited methods to behave similarly.

The goal with this design is to allow the existing writing functions to work with any `SpikeInterface` object of either version and thus no need to redesign the existing writing protocols that have been used and debugged across many conversions. The necessary code for this already exists in `v0_10_3`, but is unnecessarily tangled in an overhaul of the core writing functions that ends up breaking a lot of our existing conversion pipelines; this code merely needs to be abstracted from the `EphysWriter` class and re-implemented as a generalized Reader.

**Comment by alejoe91** [comment]
@CodyCBakerPhD note that in the new API we now have wrapper classes for [old->new recording](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/old_api_utils.py#L51-L104). currently it doesn't propagate properties, but I can make a PR that does it. Maybe this could also be a viable solution to support both types. What do you guys think?

**Comment by bendichter** [comment]
@alejoe91 this sounds great!

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Yes, that is actually exactly what we needed. Good to know it already exists; yes, propagation of properties would be the only thing then for solidifying the 1:1 mapping, and the only other thing we would need is the `add_*` and `write_*` functions here to be tested and run on `BaseRecording` objects. That way, we wouldn't really need to 'support' `spikeinterface/spikeextractors` objects here per se, just `spikeinterface/spikeinterface` ones.

**Comment by alejoe91** [comment]
> @alejoe91 Yes, that is actually exactly what we needed. Good to know it already exists; yes, propagation of properties would be the only thing then for solidifying the 1:1 mapping, and the only other thing we would need is the `add_*` and `write_*` functions here to be tested and run on `BaseRecording` objects. That way, we wouldn't really need to 'support' `spikeinterface/spikeextractors` objects here per se, just `spikeinterface/spikeinterface` ones.

I can add the property mapping on the spikeinterface side ;) Reminder to myself: https://github.com/SpikeInterface/spikeinterface/issues/426

**Comment by alejoe91** [comment]
@CodyCBakerPhD property propagation is done here: https://github.com/SpikeInterface/spikeinterface/pull/428

**Comment by bendichter** [comment]
> write_sorting tests run into a very specific error (https://github.com/catalystneuro/nwb-conversion-tools/runs/4676145276?check_suite_focus=true) using pynwb==2.0.0; this was somehow resolved along the way to master (not main) so must have been encountered at some point; likely that @Saksham20 or @alejoe91 knows what this is. A targetted PR removing the upper bound on pynwb in requirements-minimal.txt and maybe bumping the exact version in requirements-full.txt would be best here.

The problem is that there are properties of multiple data types: `val = [80, nan, nan]`. pynwb gets the data type as `int` from the first element and then fails to convert the nans, since `int` does not support NaN. We could fix this by either enforcing that all properties have the same type, or by wrapping val in `val = np.array(val)`, which in this case promotes all of the data types of floats.

**Comment by CodyCBakerPhD** [comment]
> The problem is that there are properties of multiple data types: val = [80, nan, nan]. pynwb gets the data type as int from the first element and then fails to convert the nans, since int does not support NaN. We could fix this by either enforcing that all properties have the same type, or by wrapping val in val = np.array(val), which in this case promotes all of the data types of floats.

Makes sense, that sounds like an easy fix then.

**Comment by CodyCBakerPhD** [comment]
OK everything here is now complete. `main` is now in `v0.9.5` with all the bugs fixes and changes over the last month and a half, but without the ephys refactor, which will be slowly incorporated piece by piece.

Additional tests for UnitProerties and Electrode columns is still on the to-do list.

All PRs are now up to date basing into `main`, and there is no longer a `master` branch to refer to.
