### ISSUE TITLE
no session_start_time in default metadata

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/nwb-conversion-tools#399]
While creating default metadata using `get_default_nwbfile_metadata()` [here](https://github.com/catalystneuro/nwb-conversion-tools/blob/66c1e005f48668276539365b525af67eadb4eac3/nwb_conversion_tools/utils/nwbfile_tools.py#L27) we are not creating the required `session_start_time` unlike before when we are hardcoding some value [here](https://github.com/catalystneuro/nwb-conversion-tools/commit/2adade0818ba6ae7d04828a946cc2378c1e9d908#diff-808f577549f4bcb90054540404fe667c6036259099b32701ded28001e54856d0L39). 
Is this intentional? Many of ephys data interfaces inheriting from `BaseRecordingextractorinterface` are not creating a value in their `get_metadata()`. Example: [Intan](https://github.com/catalystneuro/nwb-conversion-tools/blob/bcc38f8f0bfa46dbdab5d9963561de9163182096/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py#L66), [Neuroscope](https://github.com/catalystneuro/nwb-conversion-tools/blob/51c3824d6ce5db9e81c1f4b120a40a5c13683f37/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py#L131) and many others. So ideally converters created with these should fail.

**Comment by CodyCBakerPhD** [comment]
See Issue #354 and PR #387, as well as commit message (i.e., changelog) for version bump to 0.11.0

If you hadn't been following any of those, then I'll state it here again. `session_start_time` is now required to be present within `metadata["NWBFile"]` whenever an NWBFile is intended to be created. Some DataInterfaces auto-populate this, but many do not, in which case the user must specify it explicitly.

This is largely because we've seen more and more DANDIsets go up for review having unrealistic session start times, and since it plays such a critical role as the time basis for all contents of an NWBFile, it's really for the best that users be forced to think harder about it.
