### ISSUE TITLE
Stubbing conversions

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#479]
Recently we closed the following issue as it diverged too much from main:
https://github.com/catalystneuro/nwb-conversion-tools/pull/445

Nevertheless, the issue of which types of stubbing we should support remains and I wanted to align before we moving forward with it.

So far, we have been stubbing in two ways:

* Stub by time or frames for both recording extractors and sorting extractors.
* Stub by channels for recording extractors and by units for sorting extractors.

The first seems to be widely used as time is the dimension where the data is usually larger. 

The second one might be useful in some cases but the argument is that it reduces the fidelity of the stub way more (as we might miss properties of certain channels or units?). This is the argument in #445 and this makes sense to me. Right now, **we are planning to remove support for stubbing channels/units** which should be easy as we only use it in three of our interfaces: 1) neuralynx, 2) openephys, and 3) spickle. **Is there a good argument against this?** 

Finally, another way of controlling for size and iterate quick with conversions could be just de-activating the writing of the waveforms which should be easier with #472.

**Comment by CodyCBakerPhD** [comment]
> So far, we have been stubbing in two ways:

Have we actually? I thought these were technically unused relics in the code.


> The first seems to be widely used as time is the dimension where the data is usually larger.

For ecephys the point of comparison is really more due to sampling rates of raw data. At 20-30kHz, it would take 10's of thousands of channels to begin to compare to even a single second of a recording, and they have so much crucial metadata associated with them that for stub purposes, we need to know that that metadata is working as intended.

For units it's a similar thing since you'd typically have as many or fewer units than channels, and it's important to check that all of their metadata has been setup correctly.

> Finally, another way of controlling for size and iterate quick with conversions could be just de-activating the writing of the waveforms which should be easier with https://github.com/catalystneuro/nwb-conversion-tools/pull/472.

Similar to above, it would still be nice if this could be included in some kind of stub form. Maybe there's one of the other waveform axes we can additionally stub?

**Comment by h-mayorquin** [comment]
Thanks for expanding, @CodyCBakerPhD.

Concerning previous use, I assumed that having it in the code implied that we have used.

**Comment by CodyCBakerPhD** [comment]
> Concerning previous use, I assumed that having it in the code implied that we have used.

Hah, sometimes not always so 😉 As I recall was either included in v10 or as a pre-PR to v10 that didn't get scrubbed in the purge.

**Comment by CodyCBakerPhD** [comment]
Big point to this still open issue is we actually should support stubbing by channels, eventually. This can allow testing of time-related aspects such as observation intervals or timestamps while still only using a subset of the data

**Comment by h-mayorquin** [comment]
Should we close this? It seems that it might be useful to stub channels anyway.

**Comment by bendichter** [comment]
Let's not worry about stubbing channels until it's needed

**Comment by CodyCBakerPhD** [comment]
Keeping it in the back of the mind for the far future but for now so minor that we can close
