### ISSUE TITLE
Comments on NWBConverter

### ISSUE THREAD

**Issue by alejoe91** [catalystneuro/nwb-conversion-tools#54]
Hi guys,

I have a couple of comments about the NWBConverter class and the organization of the repo.

The NWBConverter class contains a wide range of functions to populate the Nwb file and it serves as base class for all other converters.

However, it seems to me that there are 2 very distinct kind of converters:
- Domain-specific ones (e.g. `Spikeglx2NWB` or `Miniscope2NWB` ), that populate specific subfields of the NWB file (ecephys/microscopy)
- Lab-specific ones (e.g. `ToliasNWBConverter`), that should use the different other converters to make create the entire Nwb file

For the domain-specific converters, do we really need to inherit from the `NWBConverter` class? In my opinion, the domain-specific converters could be available as functions or standalone classes of the package (building blocks) that can be then used by the lab converters to construct and populate the Nwb file. 
Put it in another way, what is the purpose for say the `Miniscope2NWB` to inherit the `create_electrode_groups` method?

Another possibility, would be to have the basw `NWBConverter` class to handle file creation all the basic metadata (subject, user, etc.), and an inherited class would make use of these basic methods (that will be similar for all labs/cases) and add some lab-specific functionalities to convert domains. 

For example: 

```python
from nwb_conversion_tools import NWBConverter
from nwb_conversion_tools.ecephys import convert_intan
from nwb_conversion_tools.ophys import convert_miniscope
from nwb_conversion_tools.behavior import convert_bpod

class BuccinoLabNWBConverter(NWBConverter):
      def __init__(self, metadata, nwbfile):
              super().__init__(nwbfile=nwbfile, metadata=metadata, source_paths=source_paths)

      def run_conversion(intan_file, miniscope_file, bpod_file, metadata):
             # each function will take care of populating the right fields of the Nwb file only
             convert_intan(self.nwbfile, intan_file, metadata)
             convert_miniscope(self.nwbfile, miniscope_file, metadata)
             convert_bpod(self.nwbfile, bpod_file, metadata)

# usage
blab_converter = BuccinoLabNWBConverter(my_metadata, 'my_file.nwb')
blab_converter.run_conversion(intan_file, miniscope_file, bpod_file, my_metadata)
```

What do you guys think?

**Comment by bendichter** [comment]
@alejoe91 thanks, this is really helpful. You are right that domain-specific and lab-specific (or more accurately experiment-specific) are two different use-cases and it might be helpful to think about them differently. This came up during the last meeting with @CodyCBakerPhD when we realized that it wouldn't really make sense to inherit from `SpikeInterface2NWBConverter` if we are converting multimodal data where we'd have another `NWBConverter` in there as well for behavior etc. It would be better to have those objects as attributes so that they can be treated the same way, but at that rate do we really benefit from them being classes? We might have cases where we want to convert a single modality, but those are rare, and when they do occur it would be straightforward to accomplish that in this structure.

The main reasons for using classes for single modalities are:
1) Sharing methods that would be common across many conversions of the same modality from different acquisition systems
2) Enforcing/encouraging the same call signature to make these function interoperable.

Really, `SpikeExtractor` and `SegmentationExtractor` accomplish both of these if we can rely on them for the domain-specific functionality. 

Do you think it would be better to define new convert functions for each type of ecephys? We could define this as something like:
```python
def convert_intan(nwbfile_path, intan_path, metadata):
    rx = IntanRecordingExtractor(intan_path)
    NwbRecordingExtractor.write_recording(rx, nwbfile_path, metadata)
```
but it might be difficult to maintain all of these functions as `SpikeInterface` grows and support more input types. Better to handle those in that project so they are all in one place. Maybe it would be better to put those two lines straight into `run_conversion`. Regardless, overall, this seems like it would reduce the complexity of this repo.

## Some minor points:
1. I'd prefer to have `run_conversion` maintain the same call signature, but that wouldn't be a big change. 
2. `metadata` and`source_paths` should either be input during `__init__` or in `run_conversion`, but I would prefer not to have it in both.

To handle both, you could just change
```python
def run_conversion(intan_file, miniscope_file, bpod_file, metadata):
```
to
```python
def run_conversion(source_paths, metadata):
```
,
```python
def run_conversion(source_paths):
```
or
```python
def run_conversion():
```


I'd be interested to hear from the rest of the team. @luiztauffer, you built much of this and put together the writer for `NwbRecordingExtractor`. @Saksham20, you are working on integrating `SegmentationExtractor`, and @CodyCBakerPhD you've been working on this project in the context of converting Buzsaki data. What do you all think?

**Comment by oruebel** [comment]
It sounds like [mixins](https://en.wikipedia.org/wiki/Mixin) might be a useful approach.

**Comment by luiztauffer** [comment]
I like the idea of the base NWBConverter dealing with basic operations (initiate file with metadata, save file, etc…), that’s how we’ve been writing it to be so far. Of course, the line between general and specific operations become blunt quick in the neurodata world, as an example consider the very first step, creating an NWB file with a value for session_start_time:
- it may come from metadata YAML file (in which case de base class handles automatically)
- it may be unknown and filled with a default value (again, the base class handles it)
- it may come from specific file format to be converted. In this case the lab-specific BuccinoLabNWBConverter (or one of the domain-specific converters it uses, such as Intan) can overwrite the create_nwbfile method

This applies to every nwb field, but of course some are more “standard” than others and in that spirit we were populating the NWBConverter with the most recurrent methods (such as create_electrode_groups) even though, as you pointed out, some domain-specific converters might never need to use all of the basic methods.

The domain-specific converters should accept existing NWB files and be able to just add information to them (instead of creating a new nwb file from scratch with the inherited methods). They should be robust enough to test for possible conflicts (e.g. testing if processing module of name ‘ecephys’ already exists, if yes use it, if not, create it) and flexible enough to be guided by metadata file instructions. 

A lab-specific `run_conversion()` method tapping into a series of domain-specific converters would then look like this:
```python
def run_conversion(intan_file, miniscope_file, bpod_file, metadata):
	converter_ophys = SystemOphys2NWB(metadata, source_files)
	converter_opyhs.operation1(*args)
	converter_opyhs.operation2(*args)
	converter_ecephys = SystemEcephys2NWB(converter_ophys.nwbfile, metadata, source_files)
	converter_ecepyhs.operation1(*args)
	converter_ecepyhs.operation2(*args)
	converter_behavior = SystemBehavior2NWB(converter_ecephys.nwbfile, metadata, source_files)
	converter_behavior.operation1(*args)
	converter_behavior.operation2(*args)
	converter_behavior.save()
```

What do you think?
I didn’t know about mixins, I’ll take a look at them!

**Comment by CodyCBakerPhD** [comment]
In terms of scalability, I agree with @bendichter in that it would become time-consuming to have a separate conversion function for every distinct ecephys type, and this would be better served by the expanding SpikeInterface whenever needed and storing that as an Extractor with guaranteed inherited functions to retrieve the necessary information. This would also reduce the amount of re-designing of the wheel that is necessary to create conversion code up for any particular lab in the future.

But we have no option against making custom conversion functions or classes on a lab-to-lab basis due to experiment specific behavioral or stimulus data; as @luiztauffer mentioned, for the more ubiquitous data types of recordings/sortings/electrodes this depends entirely upon each labs adherence to an existing standard, and the frequency of usage of that standard by other labs if we are to save time on coding by having general use, high-level classes inheriting from the NwbConverter. So ideally, to run a conversion project at optimal efficiency, the lab-specific code would be written as sparse as possible, relying on as many common conversion operations as possible and only the minimal amount of experiment-specific data would have to be added to the Nwbfile by hand.

To determine what is general enough to be required as a common domain-method, we really just need to keep track among ourselves of how often we operate with that specific formating in that specific way.

Mixins do seem interesting but would take some experimentation to see if it is worth the additional steps in logic design.

**Comment by Saksham20** [comment]
I agree with @alejoe91 that `NWBConverter` class should only contain functionality for basic metadata creation. Current functionality: 
- `NWBFile`, `Subject`, `Device` **OKAY**.
- creating electrodes/groups etc **not OK**, should be defined by a downstream ecephys class like `EcephysNWBConverter` . This is how it works for ophys data: `NWBConverter` > `OphysNWBConverter` > `ProcessedOphysNWBConverter` > `SegmentationExtractor2NWBConverter`. So the possible `EcephysNWBConverter` could have methods to create electrodes/groups etc. 
- Functionality of adding Trials table, saving etc I think **OK** since its common for all. 
---
Some suggested changes/comments for `NWBConverter`:

- How do we handle cases where there are custom classes for `Subject`, `Devices` etc? Like @luiztauffer  mentioned, we can overwrite those methods.  Why I feel this is important: in come cases, I have had to implement workarounds for a custom Subject (extended Subject class) in the downstream class. Once way to implement this could be: 
```
Class NWBConverter: 
   blah 

   def create_subject(self, metadata, subject_class=Subject):
        self.nwbfile.subject = subject_class(**metadata)

 ## similar for device
```
Coming back to what @luiztauffer brought up regarding some standard fields like `session_start_time` being dependent on lab file format, maybe we can have the functionality to overwrite the metadata before sending to the parent `NWBConverter`? This could be a strategy for any metadata that is pulled from a filetype. What do you guys think? 

I equally like the idea of @luiztauffer  that we can unlink NWBConverter with domain specific converters provided they have the ability to deal with conflicts with the input nwbfile. 

Regarding other possible changes, Mixins could solve the problem, I'm not sure how they work, I'll check them out and write my suggestions.

**Comment by alejoe91** [comment]
Thank you guys for all the comments.

@luiztauffer I have a comment about your example. In your code snippet you have:
```
        converter_ophys = SystemOphys2NWB(metadata, source_files)
	converter_opyhs.operation1(*args)
	converter_opyhs.operation2(*args)
```

Can you make an example of what operation1/operation2 could be? IMO, a domain-specific converter does 1 thing: it dumps a specific file/set of files to an existing Nwb format (and check for possible conflicts in doing so). 
That's why I think that it could very well be a function, or as @bendichter suggested, we could directly use `spikeextractors` and `segmentationextractors` in the lab-specific `run_conversion` function.

@Saksham20 @luiztauffer I think that inheriting from `NWBConverter` for lab-specific converters covers all the 3 possibilities to grab the `session_start_time`. In the third case, one would do something like this:

```
class BuccinoLabNWBConverter(NWBConverter):
      def __init__(self, metadata, nwbfile):
              super().__init__(nwbfile=nwbfile, metadata=metadata, source_paths=source_paths)

      def creatre_subject(self, metadata):
            # override one from base class
            # custom subject creation here

      def run_conversion(intan_file, miniscope_file, bpod_file, metadata):
             # grab session start time from intan
             session_start_time = retrieve_start_time_intan(intan_file)
             self.nwbfile = self.create_nwb_file(metadata, session_start_time)

             # each function will take care of populating the right fields of the Nwb file only
             convert_intan(self.nwbfile, intan_file, metadata)
             convert_miniscope(self.nwbfile, miniscope_file, metadata)
             convert_bpod(self.nwbfile, bpod_file, metadata)

# usage
blab_converter = BuccinoLabNWBConverter(my_metadata, 'my_file.nwb')
blab_converter.run_conversion(intan_file, miniscope_file, bpod_file, my_metadata)
```

Regarding mixins, I don't know if we actually need it. In Python they seem to be the same as multiple inheritance, right?
I think that we should first decide precisely on what to keep in the base class, and what to move out/handle elsewhere.

**Comment by bendichter** [comment]
OK so after talking to a few of you separately, here's what I'm thinking:

We will have two different base types `NWBConverter` will be used for combining across all of the modalities for a single experiment type. We will have another type (I'm thinking `BaseDataInterface`) for being the base class for individual modalities. One of the issues we still need to tackle is for the nwb_converter objects to provide information about what metadata is required. These objects will remain classes, and they will have the following responsibilities:
* communicate metadata requirements up the chain
* take metadata entry down the chain, and combine into modality conversion

Each child of the `BaseDataInterface` will have an attribute `metadata_schema` that will provide a json-schema-style dictionary describing the fields needed for this modality. This json-schema will contain information about what fields are fillable, what are required, what the data type is, what the default values are, and any help text that might be needed. Currently, our example YAMLs are the only things doing this job, and right now a lot of that specific information is implied. json-schema will allow us to make it explicit. 

Then (ideally) we'll be able to know what metadata any NWBConverter needs by taking the union from each of the modalities.

```python
# this json-schema should be located in a separate file such as ./default.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "metafile.schema.json",
  "title": "Schema for the metafile",
  "description": "Schema for the metafile",
  "version": "0.1.0",
  "type": "object",
  "required": ["NWBFile"],
  "additionalProperties": false,
  "properties": {
    "NWBFile": {
      "type": "object",
      "additionalProperties": false,
      "required": ["session_start_time", "keywords"],
      "properties": {
        "keywords": {
          "description": "Terms to search over",
          "type": "array",
          "items": {"title": "keyword", "type": "string"}
        },
        "experiment_description": {"type": "string", "description": "general description of the experiment"},
        "session_id": {"type": "string", "description": "lab-specific ID for the session"},
        "experimenter": {
          "description": "Name of person/people who performed experiment",
          "type": "array",
          "items": {"type": "string", "title": "experimenter"}
        },
        "identifier": {"type":  "string", "description": "A unique text identifier for the file. If one is not provided it will be randomly assigned"},
        "institution": {"type":  "string", "description": "Institution(s) where experiment is performed"},
        "lab": {"type":  "string", "description": "Lab where experiment was performed"},
        "session_description": {"type": "string", "description": "A description of the session where this data was generated"},
        "session_start_time": {"type": "string", "format": "date-time", "description": "The start date and time of the recording session"},
        "surgery": {"type": "string", "description": "Narrative description about surgery/surgeries, including date(s) and who performed surgery."},
        "pharmacology": {
          "type": "string",
          "description": "Description of drugs used, including how and when they were administered. Anesthesia(s), painkiller(s), etc., plus dosage, concentration, etc."
        },
        "protocol": {
          "type": "string",
          "description": "Experimental protocol, if applicable. E.g., include IACUC protocol"
        },
        "related_publications": {
          "type": "array",
          "items": {"title": "related publication", "type": "string"}
        },
        "notes": {"type": "string", "description": "Notes about the experiment."},
        "virus": {"type": "string", "description": "Narrative description about surgery/surgeries, including date(s) and who performed surgery."}
      }
    },
    "Subject": {
      "type": "object",
      "required": ["subject_id"],
      "properties": {
        "description": {"type": "string", "default": "no description", "description": "Description of subject and where subject came from (e.g., breeder, if animal)."},
        "genotype": {"type": "string", "description": "Genetic strain. If absent, assume Wild Type (WT)"},
        "sex": {"type": "string", "enum": ["M", "F", "U", "O"], "default": "U"},
        "species": {"type": "string", "description": "Species of subject. Use latin name."},
        "subject_id": {"type": "string", "description": "ID of animal/person used/participating in experiment (lab convention)"},
        "weight": {"type": "string", "description": "Weight at time of experiment, at time of surgery and at other important times."},
        "date_of_birth": {"type": "string", "format": "date-time", "description": "Date of birth of subject. Can be supplied instead of 'age'."}
      }
    }
	}
	}



class BaseDataInterface:

	def __init__(input_path_or_dict_of_paths):
		self.input_path = input_path

	@abstractmethod
	def get_metadata_schema(self):
		pass

	@abstractmethod
	def convert_data(self):
		pass



class IntanRecordingInterface(BaseDataInterface):
	input_path_lookup = 'intan'

	def get_metadata_schema(self):
		return {
				#dict of json-schema for SpikeInterace. May need to customize for some modalities
				}

	def convert_data(self, nwbfile_path, metadata):
		rx = IntanRecordingExtractor(self.input_path) 
		NwbRecordingExtractor.write_recording(rx, nwbfile_path, metadata)

# we can even be clever and automatically generate these classes for each RX and SX so we don't have to define a separate one for each acquisition type



class NWBConverter:

	default_metadata_schema = load_json('default.schema.json')  # somehow load the json schema declaired above

	data_interface_classes = []  # list of all data interfaces

	def __init__(self, input_paths):
		self.data_interface_objects = [data_interface(input_paths[data_interface.input_path_lookup]) for data_interface in self.data_interface_classes]

	def run_conversion():
		# default implementation will be to sequentially run each data interface, but this can be overridden as needed
		[data_interface.convert_data() for data_interface in self.data_interface]

	def compile_metadata_schema():
		metadata_schema = copy(default_metadata_schema)
		for data_interface in self.data_interface_objects:
			# combine metadata requiremets from the different modalities. This would take some care to do right, but I think it should be doable. Again, overridable as needed


# then a new experiment would be very simple:
class BuccinoLabNWBConverter(NWBConverter):
	data_interface_classes = [IntanRecordingInterface, BPodInterface]


# usage
blab_converter = BuccinoLabNWBConverter({'intan': "my_intan_path", 'bpod': 'my_bpod_path'})
expt_json_schema = blab_converter.compile_metadata_schema()
blab_converter.run_conversion(intan_file, miniscope_file, bpod_file, my_metadata)
```
