### ISSUE TITLE
Smart json updates

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#61]
Current formats for performing updates to the fields 'properties' and 'required' in the json schema are done in the current way

```
        for name, data_interface in self.data_interface_objects.items():
            this_schema = data_interface.get_metadata_schema()
            metadata_schema['properties'].update({name: this_schema['properties']})
            for field in this_schema['required']:
                metadata_schema['required'].append(field)
```

but a better way would be to have a merge function between two individual schemas such that the result of the merge robustly updates the appropriate field at the appropriate nesting level as well. I'll post an idea for such a function a bit later.

**Comment by bendichter** [comment]
So I think we decided to keep the modality-specific divisions (e.g. 'Ecephys') because it allows us to easily share metadata between interfaces, e.g. sharing the starting time and sampling rate between the sorting and recording interfaces. So making a few adjustments, we'd have:

```python
for data_interface in self.data_interface_objects.values():
    this_schema = data_interface.get_metadata_schema()
    metadata_schema['Ecephys']['properties'].update({this_schema['properties']})
    for field in this_schema['required']:
        if field not in metadata_schema['Ecephys']['required']:
            metadata_schema['required'].append(field)
```

it might be nice to have an API that allowed something like

```python
for data_interface in self.data_interface_objects.values():
    this_schema = data_interface.get_metadata_schema()
    schema_obj.Ecephys.merge(this_schema)

json_schema_dict = schema_obj.to_dict()
```

It would also be nice to catch places in this merge where the key already exists in both dicts and the values are different.

I'm just playing around with syntax at this point. What do you all think? Not mission-critical at this point, but could be worth looking into.

**Comment by CodyCBakerPhD** [comment]
For sure, that merge function is precisely the calling behavior I was thinking of. Having the schema be an instance of a general class in itself though would be even better, but yeah at that point it definitely deserves to be in its own separate repository.

I'll start working on this after I get the robustness of the Yuta converter over the entire dataset hammered out (as I check other sessions, there are even more special cases for stuff like the .clu and .res formatting that I had not seen, and break the current function versions in SpikeInterface, but are also easy fixes).

**Comment by luiztauffer** [comment]
Hi guys, just found this issue now, I believe I solved it with the current PR #59

**Comment by bendichter** [comment]
Yes, I think that will be sufficient for now

**Comment by bendichter** [comment]
Yes, I think #59 handles most of what we need. If there are any needs that come up, we can re-open this issue
